### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by TedLivist** [HENRYKC24/to-do-list-draggable#23]
#### Your code looks and works just fine. The extra features are very much interesting too.
The following are mere suggestions:
- Update `README` to contain code for running JavaScript linter
- There is redundancy in your UI with respect to the `Add` button function. 
  - You have 2 `Add` buttons. One should do since they are close to each other on the page, anyways
- Your `ReSync` feature also has the same redundancy issue as the `Add` functionality on your UI.

**Comment by HENRYKC24** [comment]
Thank you very much, peers. I really appreciate that.
