### ISSUE TITLE
Morning session Peer to Peer code review

### ISSUE THREAD

**Issue by aliabbani** [HENRYKC24/to-do-list-draggable#4]
# The project is actually really good. ⭐ 🥇 
Hello Henry you have done a great job. We think that your project is completed. ✔️ 
But we think as a group reviewing your code you can still improve your project though on one aspect : 
## ⬆️ 

- The color of the hover in the navigation bar can be better. Please try to change it or you can remove it.

**Comment by HENRYKC24** [comment]
Thank you so much @aliabbani :handshake: 
I have worked on the navbar item on hover color and I really like how it looks presently.
I really appreciate:pray:
